### ISSUE TITLE
build for systemd-239-18 el8.1

### ISSUE THREAD

**Issue by bcg62** [FelixSchwarz/epel8-networkd#1]
Would you be able to build this for systemd-239-18 which is in the CR repo for centos8.1 soon to be released?

Thanks!

```
# dnf list systemd.x86_64
Last metadata expiration check: 0:00:01 ago on Tue Jan  7 20:08:21 2020.
Installed Packages
systemd.x86_64                                                                                                                     239-13.el8                                                                                                                      @System
Available Packages
systemd.x86_64                                                                                                                     239-18.el8                                                                                                                      cr
```

**Comment by FelixSchwarz** [comment]
I'll try to do that shortly. In the meantime you can try the branch [systemd-239-18](https://github.com/FelixSchwarz/epel8-networkd/tree/systemd-239-18) I created a while ago.

**Comment by bigHosting** [comment]
+1 

CentOS 8.1 is finally out. For now I've excluded systemd* from dnf update.

**Comment by FelixSchwarz** [comment]
I'm working on a new build right now.

**Comment by FelixSchwarz** [comment]
New build is available and works for me:
https://copr.fedorainfracloud.org/coprs/fschwarz/systemd-networkd/build/1147971/

**Comment by bigHosting** [comment]
This is awesome! Thank you, I'll test tonight and report back any issues.

**Comment by FelixSchwarz** [comment]
you are welcome. I check switched two machines to the new package version and both rebooted without problems.
